bool gaussianBlur1
bool gaussianBlur2
bool medianBlur1
bool medianBlur2
bool morphOpen
bool pruning
float64 gaussianKernel1
float64 gaussianKernel2
float64 medianKernel1
float64 medianKernel2
float64 morphOpenIterations
float64 pruningIterations
string skeletonizationMethod
---
float64 result
geometry_msgs/Point[] voronoi1
geometry_msgs/Point[] vertices1
geometry_msgs/Point[] voronoi2
geometry_msgs/Point[] vertices2
geometry_msgs/Point[] matchedVertices1
geometry_msgs/Point[] matchedVertices2
