string method
string detector
string descriptor
string matcher
string matchingMethod
string closestPointMethod
string distNorm
float64 matchingRatio
float64 ransacReprjError
bool scaleMapsBrushfire
bool morphologicalFiltering
bool binary
bool manualAlignment
bool gaussianBlur1
bool gaussianBlur2
bool medianBlur1
bool medianBlur2
float64 gaussianKernel1
float64 gaussianKernel2
float64 medianKernel1
float64 medianKernel2
ogm_communications/MapPose transform
nav_msgs/OccupancyGrid groundTruthMap
nav_msgs/OccupancyGrid slamMap
---
float64 result
float64 acceptance
float64 overlapArea
float64 quality
float64 meanExTime
int64 matches
sensor_msgs/Image featuresImage
sensor_msgs/Image initialMatchedImage
sensor_msgs/Image finalMatchedImage
sensor_msgs/Image mergedImage
