string method
string detector
string descriptor
string matcher
string matchingMethod
string closestPointMethod
string distNorm
float64 matchingRatio
float64 ransacReprjError
bool scaleMapsBrushfire
bool binary
bool manualAlignment
ogm_msgs/MapPose transform
---
float64 result
