string method
string detector
string descriptor
string matcher
string closestPointMethod
string distNorm
float64 matchingRatio
float64 ransacReprjError
bool binary
bool manualAlignment
ogm_msgs/MapPose transform
nav_msgs/OccupancyGrid groundTruthMap
nav_msgs/OccupancyGrid slamMap
---
float64 result
